### PR TITLE
Update string literal comparison

### PR DESCRIPTION
**Pull request by elacuesta**

### CODE REVIEW

**Comment by Gallaecio** [comment]
Based on [this](https://github.com/Chia-Network/chia-blockchain/issues/603#issuecomment-753368835), switching from [xenial](https://github.com/scrapy-plugins/scrapy-jsonschema/blob/master/.travis.yml#L3) to something newer may do the trick.

**Comment by Gallaecio** [comment]
[It worked](https://github.com/scrapy-plugins/scrapy-jsonschema/pull/28).

**Review by Gallaecio — COMMENTED** [review]
:heavy_check_mark: provided changes to `.travis.yml` are reverted in favor of #28.

**Comment by elacuesta** [comment]
Rebased and squashed for simplicity

**Pull request merged**
